# Generated by Django 3.2 on 2024-06-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="pt_id",
            new_name="post",
        ),
    ]
